### ISSUE TITLE
Could you share the training codes?

### ISSUE THREAD

**Issue by chenshen03** [HighwayWu/ImageForensicsOSN#1]
Thank you for sharing, it's really a great work!
And when will the training code be open sourced?

**Comment by HighwayWu** [comment]
The training code will be released after the project-related patents are accepted (expected within the year).

**Comment by bjtuln** [comment]
I'm interested in this work too.
When is the training code expected to be shared?

**Comment by wang-qichang** [comment]
I'm interested in this work too.
