### ISSUE TITLE
Could you help me?

### ISSUE THREAD

**Issue by DreamerLuu** [HighwayWu/ImageForensicsOSN#11]
Hello, dear author. I greatly admire your work. I have been attempting to reproduce your experimental results, but as a beginner, I am slightly lacking in skills and have encountered some difficulties. Could you please share the Dresden dataset and  the related code for setting up the training set?

**Comment by HighwayWu** [comment]
Thanks for your interest. Actually, we found a more suitable training dataset (i.e., the dataset used in CAT-Net, which can be downloaded from https://github.com/mjkwon2021/CAT-Net). And it would be more fair to compare with similar methods, e.g., TruFor (CVPR'23).
