### ISSUE TITLE
Confused about the weight of SE-Unet

### ISSUE THREAD

**Issue by yuxiaoxiangyong** [HighwayWu/ImageForensicsOSN#12]
Great job! Your contribution to the field of image forgery localization is impressive. Apologies for the interruption. I'm a bit puzzled—does the pretrained weights of the Unet imply training it on the ImageNet dataset or specifically on a manipulation dataset?

**Comment by HighwayWu** [comment]
Thanks for your interest. The SCSE-UNet weights released on this [link](https://drive.google.com/file/d/1scOAVxvqYSfRi4s7s0crk2Ieqn5Cm6r6/view?usp=sharing) is trained on a manipulation dataset. While the UNet weights from this [link](https://drive.google.com/file/d/1jbVCBc4ofj3oASKEOtxEtuAw6cBl8wfv/view?usp=sharing) is trained on Facebook transmission dataset. Both of the above weights are trained based on an ImageNet initialization weights.

**Comment by yuxiaoxiangyong** [comment]
Thank you for your response! I wish success for your most recent work's acceptance this year!
