### ISSUE TITLE
文件

### ISSUE THREAD

**Issue by bai-0829** [HighwayWu/ImageForensicsOSN#13]
大佬，train.py里的  self.osn_net.load_state_dict(torch.load('weights/OSN_Unet_Residual_JPEG_module/U_Net_weights.pth')) 这个pth在哪里下载呀

**Comment by HighwayWu** [comment]
It can be downloaded from [Google Drive](https://drive.google.com/file/d/1jbVCBc4ofj3oASKEOtxEtuAw6cBl8wfv/view?usp=sharing) or [Baidu Pan](https://pan.baidu.com/s/1bMAUTOoOYBx1ZpReskCFpA?pwd=bsun).

**Comment by bai-0829** [comment]
但是我打开连接后下载文件名字为“OSN_UNet_weights.pth“,而且我在osn.py文件中发现了这句代码”pretrained = torch.load('weights/OSN_UNet_weights.pth')”,train.py文件中需要的的是U_Net_weights.pth，这两个权重文件是一样的吗？

**Comment by HighwayWu** [comment]
是一样的，我之后会更正osn.py中要读取的权重文件名与下载文件名一致。感谢指出该错误！
