### ISSUE TITLE
一些疑问？

### ISSUE THREAD

**Issue by Linql7** [HighwayWu/ImageForensicsOSN#14]
首先，对您的工作作出肯定，由于本人知识浅薄，仍存在一些疑问？
1、文中对detector检测器也就是SE-UET进行了较少的介绍，并指出本检测器能够在未经历噪声干扰的实验中获得较好的效果，我比较好奇您的seuet架构，也就是您提出baseline。
2、train.py中。是包含对network g（噪声建模器）和detector f 的训练过程吗？

**Comment by HighwayWu** [comment]
Thanks for your question.
1) The architecture of SE-UNet can refer to the one we used in the [competition](https://github.com/HighwayWu/Tianchi-FFT2). It mainly uses a spatial-temporal attention module to enhance the learned forensic features.
2) osn.py is used to train the noise simulator. After training, we can use train.py to train a detector against this noise simulator.
