### ISSUE TITLE
训练集规模

### ISSUE THREAD

**Issue by zijieloooooou** [HighwayWu/ImageForensicsOSN#15]
请问训练ImageForensicsOSN的定位算法用的训练集规模有多大？精确到万即可。万分感谢！

**Comment by HighwayWu** [comment]
Thanks for your asking. Our training set roughly contains 15k data, and please refer to a similar data generation [method](https://github.com/jawadbappy/forgery_localization_HLED/tree/master/synthetic_data). In addition, it is recommended to use the training set of [CAT-Net](https://github.com/mjkwon2021/CAT-Net), which can provide richer forgery types to improve the generalization of the detector.
