### ISSUE TITLE
关于数据集预处理问题:image size=896

### ISSUE THREAD

**Issue by Linql7** [HighwayWu/ImageForensicsOSN#17]
作者您好,请问您是否可以提供关于数据预处理的脚本,我观察到您要求输入图像的尺寸image size 必须为896,但实际我们使用自己的数据集进行train时,图片尺寸大都不符合.祝您科研工作顺利.

**Comment by HighwayWu** [comment]
感谢您的提问，本项目训练及测试时图像尺寸并不强制为896x896。限于当时资源，训练时所使用的图像尺寸为256x256，而测试时最大可接受896x896。建议您: 1）根据资源情况可将训练尺寸设置为512x512甚至1024x1024；2）将数据进行上/下采样或裁剪等预处理以满足训练/测试要求，可参考[此处](https://albumentations.ai/docs/api_reference/augmentations/geometric/resize/#albumentations.augmentations.geometric.resize.Resize)。祝您科研顺利。

**Comment by Linql7** [comment]
感谢您的回答。我还有另外一个问题。
在评估阶段，test dataset中的CASIA实际有两个版本：CASIA V1 （约900张图片）CASIAV2(约5000张图片)
请问您的结果是在V1版本的数据集还是在V2的数据集上，还是两个版本都使用了。
期待您的回复。

**Comment by HighwayWu** [comment]
是在CASIA V1，具体使用的测试图片可以从[这里](https://drive.google.com/file/d/1uMNZdhX3bYAZNcVGlkCvrnj5lSLW1ld5/view?usp=sharing)下载。
