### ISSUE TITLE
so the stage1,2,3 works for imitating the noise caused by OSN？

### ISSUE THREAD

**Issue by kkpssr** [HighwayWu/ImageForensicsOSN#4]
thanks for excellent work, So If only retrain final detectors in own datasets, will it influence the final pefermance ？

**Comment by HighwayWu** [comment]
Thanks for your question. Yes, the stage 1,2,3 aim to imitate the OSN noise, and are used for training the final detector. Without them, the final performance will not be influenced.

**Comment by kkpssr** [comment]
您好，可以+qq向您请教下篡改识别的训练方法么？



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 6, 2023 14:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HighwayWu/ImageForensicsOSN] so the stage1,2,3 works for imitating the noise caused by OSN？ (Issue #4)




 
Thanks for your question. Yes, the stage 1,2,3 aim to imitate the OSN noise, and are used for training the final detector. Without them, the final performance will not be influenced.
