### ISSUE TITLE
Could you share the WEI dataset and the training code for the network that simulates OSN's noise?

### ISSUE THREAD

**Issue by Gang-plank** [HighwayWu/ImageForensicsOSN#5]
I admire your experiment very much, but I have encountered some troubles when trying to implement the algorithm.

**Comment by HighwayWu** [comment]
Thank you for your admiration. We will upload the code for training simulated OSN network and the WEI dataset ASAP.

**Comment by HighwayWu** [comment]
The WEI dataset can be downloaded from this link: https://pan.baidu.com/s/1GYL3Zaom9r2TjzPhkVOjwQ?pwd=fdww

**Comment by HITZhoushenglie** [comment]
Thank you for sharing your code! But I'm still confused about parts of the code.
1) osn about wechat, weibo, whatsapp train detail and datasets downdloade link.
2) The description of the adversarial sample algorithm used in adversarial training in the source code seems inconsistent with the original text.
