### ISSUE TITLE
大佬，能发布一下篡改检测器预训练的数据集吗？

### ISSUE THREAD

**Issue by Viktorjc98** [HighwayWu/ImageForensicsOSN#6]
大佬，能发篡改一下训练检测器的预训练的数据集吗？我用自己合成的数据集训练效果不太好！

**Comment by HighwayWu** [comment]
可以参考去年相关的论文（https://github.com/mjkwon2021/CAT-Net），他们制作了含有60万张的大型伪造数据集。应该会比我当时的训练集效果更好。
