### ISSUE TITLE
Could you help me study your paper

### ISSUE THREAD

**Issue by DreamerLuu** [HighwayWu/ImageForensicsOSN#8]
Hello, I have just started learning this knowledge and I have the opportunity to read your paper. I admire your paper very much, but it has a certain difficulty for me. I want to run through your experimental code. May I ask how to obtain train.npy

**Comment by HighwayWu** [comment]
Thanks for your attention. The train.npy is actually a list and should have the following format:
[
  (path_of_input1, path_of_ground_truth1),
  (path_of_input2, path_of_ground_truth2),
  ...
]
You may use numpy lib to save this .npy file.

**Comment by DreamerLuu** [comment]
Thank you for your help, but I have encountered a new problem. May I ask what the 'choice' in the constructor is when instantiating Mydataset

**Comment by HighwayWu** [comment]
'choice' is to control whether to use data augmentation (i.e., resize, compression, etc.) for the current data, and is usually used during training. So, just set it to 'train' if this dataset is used for training, and set it to else if this dataset is for testing.
