### ISSUE TITLE
How to generate the train.npy

### ISSUE THREAD

**Issue by dengdd7561** [HighwayWu/ImageForensicsOSN#9]
Hello, Readme mentioned "The data file 'train.npy 'should be prepared in advance", so what does “path of ground truth” mean?

**Comment by HighwayWu** [comment]
The train.npy is actually a list and should have the following format:
[
(path_of_input1, path_of_ground_truth1),
(path_of_input2, path_of_ground_truth2),
...
]
You may use numpy lib to save this .npy file.

“path of ground truth” means the mask of the forgery data.
